const data = {
  products: [
    {
      name: 'Puma Slim shirt',
      slug: 'puma-slim-shirt',
      category: 'Shirts',
      image: '/images/puma-1.jpg',
      price: 75,
      countInStock: 15,
      brand: 'Puma',
      rating: 4.6,
      numReviews: 5,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/nike-1.jpg',
      price: 98,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Raymonds shirt',
      slug: 'raymonds-shirt',
      category: 'Shirts',
      image: '/images/raymond-1.jpg',
      price: 99,
      countInStock: 25,
      brand: 'Raymonds',
      rating: 4.5,
      numReviews: 23,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Pants',
      slug: 'adidas fit pants',
      category: 'Pants',
      image: '/images/adidas-1.jpg',
      price: 85,
      countInStock: 25,
      brand: 'Adidas',
      rating: 4.6,
      numReviews: 5,
      description: 'high quality pants',
    },
  ],
};

export default data;
